use homit;

/* Insert super categories */
INSERT INTO `catalog_super_categories`(id, name, display_name, image) VALUES(1 ,"liquor-station" ,"Liquer Station" ,"liquor-station_store.jpeg");
INSERT INTO `catalog_super_categories`(id, name, display_name, image) VALUES(2 ,"safeway" ,"Snack Vendor" ,"snack-vendor_store.jpeg");
INSERT INTO `catalog_super_categories`(id, name, display_name, image) VALUES(3 ,"convenience" ,"Snack Vendor" ,"snack-vendor_store.jpeg");
INSERT INTO `catalog_super_categories`(id, name, display_name, image) VALUES(4 ,"homitcar" ,"Snack Vendor" ,"snack-vendor_store.jpeg");

/* Insert stores */
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (1, "Homit Store", "Calgary, AB", "0", "0", "4038003460", "4", "00:00:00", "00:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (100, "Liquor Depot", "3630 Brentwood Rd NW, Calgary, AB T2L 1K8", "51.0869109", "-114.1277174", "4032892946", "1", "10:00:00", "23:59:59", "00:00:00", "02:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (101, "Liquor Depot", "5032 16 Ave NW, Calgary, AB T3B 0N3", "51.0741680999999", "-114.1652687", "4032479030", "1", "10:00:00", "23:59:59", "00:00:00", "02:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (102, "Liquor Depot", "5005 Dalhousie Dr NW, Calgary, AB T3A 1B2", "51.1054065999999", "-114.1616697", "4032021088", "1", "10:00:00", "23:59:59", "00:00:00", "02:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (103, "Liquor Depot", "1810 14 Ave NW, Calgary, AB T2N 1M7", "51.066099", "-114.10225", "4032960745", "1", "10:00:00", "23:59:59", "00:00:00", "02:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (104, "Liquor Depot", "831 Edmonton Trail NE, Calgary, AB T2E 3J8", "51.0595663999999", "-114.054754099999", "4032775499", "1", "10:00:00", "23:59:59", "00:00:00", "02:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (105, "Liquor Depot", "550 64 Ave NE, Calgary, AB, T2K 6A9", "51.111396", "-114.055103799999", "4032961875", "1", "10:00:00", "23:59:59", "00:00:00", "02:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (106, "Safeway Brentwood", "3636 Brentwood Rd NW, Calgary, AB T2L 1K8", "51.0853289999999", "-114.124191", "4032891424", "2", "08:00:00", "23:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (107, "Safeway MarketMall", "3625 Shaganappi Trail NW, Calgary, AB T3A 0E2", "51.0846392", "-114.155410099999", "4032865510", "2", "08:00:00", "23:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (108, "Safeway Montgomery", "5048 16 Ave NW, Calgary, AB T3B 0N3", "51.0749250999999", "-114.1660517", "4032883219", "2", "08:00:00", "23:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (109, "Safeway NorthHill", "1632 14 Avenue NW, Calgary, AB T2N 1M7", "51.066206", "-114.1012165", "4032100002", "2", "08:00:00", "23:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (110, "Safeway Sunnyside", "410 10 St NW, Calgary, AB T2N 1V9", "51.0561809", "-114.085240199999", "4032703054", "2", "08:00:00", "23:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (111, "Safeway Beacon Heights", "1818 Centre Street NE, 20, Calgary, AB T2P2S6", "51.0683476", "-114.0611207", "4032763328", "2", "08:00:00", "23:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (112, "Safeway Thorncliffe", "5607 4 St NW, Calgary, AB T2K 1B3", "51.1018284", "-114.072880699999", "4037304955", "2", "08:00:00", "23:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (113, "Safeway Dalhousie", "5005 Dalhousie Drive NW, Calgary, AB T3A5R8", "51.1054065999999", "-114.1616697", "4032020425", "2", "08:00:00", "23:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (114, "7-eleven", "6306 Bowness Rd NW, Calgary, AB T3B 0E5", "51.0852777", "-114.1781356", "4032863588", "3", "00:00:00", "23:59:59", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (115, "7-eleven", "4444 16 Ave NW, Calgary, AB T3B 0M4", "51.0690215", "-114.1587322", "4032882164", "3", "00:00:00", "23:59:59", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (116, "7-eleven", "2604 Kensington Rd NW, Calgary, AB T2N 3S5", "51.052756", "-114.120581599999", "4032835200", "3", "23:59:59", "00:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (117, "7-eleven", "311 16 Ave NE, Calgary, AB T2E 1K1", "51.0665286", "-114.0569338", "4032771041", "3", "00:00:00", "23:59:59", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (118, "7-eleven", "402 20 Ave NE, Calgary, AB T2E 1R2", "51.071005", "-114.0558704", "4032764226", "3", "00:00:00", "23:59:59", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (119, "7-eleven", "2417 4 St NW, Calgary, AB T2M 2Z8", "51.0739572", "-114.0720764", "4032899845", "3", "00:00:00", "23:59:59", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (120, "7-eleven", "4105 4 St NW, Calgary, AB T2K 1A3", "51.0879057", "-114.072426", "4035091120", "3", "00:00:00", "23:59:59", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (121, "7-eleven", "5003 Centre St NW, Calgary, AB T2K 0S9", "51.0963169", "-114.062861", "4032751394", "3", "00:00:00", "23:59:59", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (122, "7-eleven", "920 Northmount Dr NW, Calgary, AB T2L 0A9", "51.086695", "-114.103784", "4032691462", "3", "00:00:00", "23:59:59", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (123, "7-eleven", "1339 Northmount Dr NW, Calgary, AB T2L 0C9", "51.0926441", "-114.1287754", "4032823315", "3", "00:00:00", "23:59:59", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, phone_number, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (124, "7-eleven", "4615 Valiant Dr NW, Calgary, AB T3A 0Y2", "51.0903989", "-114.1537538", "4032884315", "3", "00:00:00", "23:59:59", "00:00:00", "00:00:00");

/* Insert categories */
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(1, "beer", "Beer", 1);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(2, "wine", "Wine", 1);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(3, "spirit", "Spirit", 1);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(4, "liqueur", "Liqueur", 1);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(5, "snack", "Snack", 2);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(6, "snack", "Snack", 3);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(7, "beverage", "Beverage", 2);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(8, "beverage", "Beverage", 3);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(9, "beverage", "Beverage", 4);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(10, "party-supply", "Party-Supply", 4);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(11, "party-supply", "Party-Supply", 2);

/* Insert subcategories*/
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(1, "Lager", 1);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(2, "Witbier", 1);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(3, "Pilsner", 1);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(4, "Ale", 1);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(5, "Cider", 1);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(6, "IPA", 1);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(7, "Irish Dry Stout", 1);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(8, "White Wine", 2);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(9, "Red Wine", 2);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(10, "Rose Wine", 2);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(11, "Sparkling Wine", 2);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(12, "Sake", 2);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(13, "Fortified Wine", 2);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(14, "Vodka", 3);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(15, "Whiskey", 3);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(16, "Tequila", 3);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(17, "Brandy", 3);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(18, "Rum", 3);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(19, "Gin", 3);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(20, "Herbal", 4);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(21, "Cream", 4);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(22, "Fruit", 4);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(23, "Blended", 4);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(24, "Coffee", 4);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(25, "Popcorn & Chips", 5);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(26, "Popcorn & Chips", 6);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(27, "Meat & Cheese", 5);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(28, "Meat & Cheese", 6);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(29, "Nut Mix & Tray", 5);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(30, "Confectionery", 5);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(31, "Confectionery", 6);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(32, "Sauce & Seasoning", 5);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(33, "Sauce & Seasoning", 6);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(34, "Soda & Juice", 7);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(35, "Soda & Juice", 8);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(36, "Water & Ice", 7);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(37, "Water & Ice", 8);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(38, "Soda & Juice", 9);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(39, "Energy Drink", 7);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(40, "Energy Drink", 8);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(41, "Plastic & Paper", 10);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(42, "Games & Décor", 11);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(43, "Barware", 10);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(44, "Plastic & Paper", 11);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(45, "Games & Décor", 10);

/* Insert types */
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(1, "Pale Lager", 1);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(2, "Wheat Ale", 2);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(3, "Dortmunder", 1);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(4, "Pale Lager", 3);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(5, "Brown Ale", 4);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(6, "Kristalweizen", 4);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(7, "Dark Lager", 1);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(8, "Czech Style", 3);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(9, "Hard Cider", 5);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(10, "India Pale Ale", 6);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(11, "Adjunct Lager ", 1);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(12, "Light Lager", 1);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(13, "Fruit Beer", 1);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(14, "German Pilsner", 3);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(15, "Amber Lager", 1);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(16, "Fruit Beer", 4);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(17, "Cream Ale", 4);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(18, "Pale Ale", 4);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(19, "American IPA", 6);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(20, "Wheat Ale", 4);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(21, "Scottish Style", 4);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(22, "English Pale Ale", 6);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(23, "Japanese Rice Lager", 1);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(24, "Amber Ale", 4);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(25, "Original Cider", 5);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(26, "Fruit Cider", 5);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(27, "Flower Cider", 5);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(28, "Irish Style", 7);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(29, "American Lager", 1);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(30, "Danish Style", 5);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(31, "Pinot Grigio", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(32, "Cabernet Sauvignon", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(33, "Shiraz", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(34, "Cabernet Merlot", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(35, "Sauvignon Blanc", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(36, "Merlot", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(37, "Moscato", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(38, "Chardonnay", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(39, "Rose", 10);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(40, "Champagne", 11);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(41, "Big Bang Theory", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(42, "Hatfield's Fuse", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(43, "Smooth White", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(44, "Pinot Noir", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(45, "Riesling", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(46, "Malbec", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(47, "Ice Wine", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(48, "Red Blend", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(49, "White Blend", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(50, "Inferno", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(51, "Syrah", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(52, "Pink Moscato", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(53, "Zinfandel", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(54, "White Zinfandel", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(55, "Pinot Grigio", 11);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(56, "Zinfandel", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(57, "Sake", 12);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(58, "Vermouth", 13);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(59, "Aperitif Wine", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(60, "Viognier", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(61, "Sparkling Red", 11);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(62, "Chianti", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(63, "Blend", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(64, "Corvina", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(65, "Prosecco", 11);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(66, "Pinot Noir Rose", 10);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(67, "Sherry", 13);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(68, "Blend", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(69, "Flavorless Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(70, "Peach Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(71, "Vanilla Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(72, "Lime Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(73, "Mandarin Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(74, "Cytrus Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(75, "Lemon Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(76, "Lemon & Lime Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(77, "Cherry Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(78, "Grape Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(79, "Green Apple Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(80, "Orange Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(81, "Malt Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(82, "Raspberry Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(83, "Blueberry Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(84, "Pineapple Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(85, "Red Berry Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(86, "Tropical Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(87, "Bourbon", 15);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(88, "Rye", 15);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(89, "Blended", 15);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(90, "Irish", 15);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(91, "Scotch", 15);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(92, "Oaked", 15);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(93, "Single Malt", 15);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(94, "Irish Cream", 15);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(95, "Reposado Tequila", 16);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(96, "Gold Tequila", 16);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(97, "Silver Tequila", 16);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(98, "Anejo Tequila", 16);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(99, "Lime Tequila", 16);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(100, "Cognac", 17);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(101, "Spiced Rum", 18);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(102, "Black Spiced Rum", 18);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(103, "White Rum", 18);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(104, "Gold Rum", 18);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(105, "Blended", 18);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(106, "Blended", 19);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(107, "Dry Gin", 19);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(108, "Herbal Liqueur", 20);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(109, "Irish Liqueur", 21);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(110, "Apple Liqueur", 22);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(111, "Grape Liqueur", 22);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(112, "Raspberry Liqueur", 22);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(113, "Watermelon Liqueur", 22);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(114, "Hezelnut Liqueur", 20);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(115, "Blended Liqueur", 23);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(116, "Black Raspberry Liqueur", 22);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(117, "Fruit Liqueur", 22);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(118, "Coffee Liqueur", 24);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(119, "Cream Liqueur", 21);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(120, "Infused Wine", 22);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(121, "Classic Chips", 25);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(122, "Classic Chips", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(123, "Sour Cream & Onion Chips", 25);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(124, "Sour Cream & Onion Chips", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(125, "Cheddar Cheese Chips", 25);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(126, "Barbecue Chips", 25);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(127, "Cheesy Chips", 25);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(128, "Cheesy Chips", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(129, "Cheddar Jalapeno", 25);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(130, "Cheddar Jalapeno", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(131, "Salt & Vinegar Chips", 25);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(132, "Salt & Vinegar Chips", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(133, "Cheese & Onion Popcorn", 25);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(134, "Cheese & Onion Popcorn", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(135, "White Cheddar Popcorn", 25);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(136, "White Cheddar Popcorn", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(137, "Cheddar Jalapeno Popcorn", 25);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(138, "Beef Jerky", 27);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(139, "Beef Jerky", 28);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(140, "Pork Jerky", 27);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(141, "Pork Jerky", 28);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(142, "Chicken Jerky", 27);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(143, "Chicken Jerky", 28);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(144, "All Dressed Chips", 25);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(145, "Cheesy Nachos", 25);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(146, "Double Cheesy Nachos", 25);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(147, "Cheesy Nachos", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(148, "Double Cheesy Nachos", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(149, "Tortilla Chips", 25);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(150, "Tortilla Chips", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(151, "Spicy Pistachos", 29);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(152, "Salty Pistachos", 29);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(153, "Roasted Pistachos", 29);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(154, "Peanut", 29);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(155, "Strawberry Twizzler", 30);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(156, "Strawberry Twizzler", 31);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(157, "Classic Chocolate ", 30);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(158, "Classic Chocolate ", 31);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(159, "Hazelnut Chocolate ", 30);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(160, "Hazelnut Chocolate ", 31);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(161, "White Chocolate", 30);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(162, "White Chocolate", 31);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(163, "Cookies & Cream Chocolate", 30);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(164, "Cookies & Cream Chocolate", 31);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(165, "Dark Chocolate", 30);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(166, "Ranch Dip", 32);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(167, "Ranch Dip", 33);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(168, "Red Pepper Salsa", 32);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(169, "Garlic Salsa", 32);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(170, "Spinach Dip", 32);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(171, "Spicy Salsa", 32);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(172, "Red Pepper Salsa", 33);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(173, "Garlic Salsa", 33);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(174, "Spinach Dip", 33);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(175, "Spicy Salsa", 33);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(176, "Salt & Vinegar Seasoning", 32);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(177, "Ketchup Seasoning", 32);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(178, "White Cheddar Seasoning", 32);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(179, "Popcorn Bags", 25);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(180, "Edam Cheese", 27);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(181, "Assorted Cheese", 27);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(182, "Salami Combo", 27);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(183, "Vegetable Tray", 29);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(184, "Fruit Tray", 29);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(185, "Classic Soda", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(186, "Classic Soda", 35);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(187, "Diet Soda", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(188, "Diet Soda", 35);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(189, "Ginger Ale Soda", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(190, "Ginger Ale Soda", 35);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(191, "Classic Water", 36);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(192, "Classic Water", 37);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(193, "Raspberry Limonade", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(194, "Raspberry Limonade", 35);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(195, "Orange Limonade", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(196, "Orange Limonade", 35);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(197, "Tonic Water", 36);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(198, "Cranberry Juice", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(199, "Classic Clamato", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(200, "Classic Clamato", 35);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(201, "Spicy Clamato", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(202, "Lemon Juice", 38);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(203, "Lime Juice", 38);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(204, "Blend Juice", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(205, "Pineapple Juice", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(206, "Mango Juice", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(207, "Diet Energy Drink", 39);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(208, "Diet Energy Drink", 40);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(209, "Classic Energy Drink", 39);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(210, "Classic Energy Drink", 40);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(211, "Ice", 36);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(212, "Ice", 37);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(213, "Classic Sparkling Water", 36);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(214, "Lemon & Orange Sparkling Water", 36);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(215, "Classic Sparkling Water", 37);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(216, "Lemon & Orange Sparkling Water", 37);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(217, "Plastic Cup", 41);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(218, "Candle", 42);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(219, "Classic Beer Opener", 43);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(220, "Bottle Opener", 43);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(221, "Plastic Plate", 41);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(222, "5mm Flexible Straw", 41);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(223, "20 oz Plastic Shot", 41);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(224, "Heavy Weight Plastic Cutlery Set 40x20x20", 41);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(225, "Plastic Fork", 41);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(226, "Plastic Teaspoon", 41);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(227, "Plastic Knives", 41);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(228, "Free Flow Metal Liquor Pourer", 43);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(229, "30oz Coctail Shaker", 43);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(230, "Classic Shape 15oz Wine Glass", 43);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(231, "152mm Paddle Skewer", 43);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(232, "2-ply Facial Tissue Napkin", 41);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(233, "Mint Toothpicks", 43);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(234, "2-ply Paper Towel", 44);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(235, "Red Playing Cards", 45);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(236, "Table Tennis Balls", 45);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(237, "Shot Glass", 43);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(238, "Wine Sealer", 43);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(239, "Sealing Cleap", 43);

/* Insert packaging types */
INSERT INTO `catalog_containers`(id, name) VALUES(1, "bottle");
INSERT INTO `catalog_containers`(id, name) VALUES(2, "can");
INSERT INTO `catalog_containers`(id, name) VALUES(3, "object");
INSERT INTO `catalog_containers`(id, name) VALUES(4, "bar");
INSERT INTO `catalog_containers`(id, name) VALUES(5, "pack");
INSERT INTO `catalog_containers`(id, name) VALUES(6, "jar");

/* Insert packagings */
INSERT INTO `catalog_packagings`(id, name) VALUES(1, "1");
INSERT INTO `catalog_packagings`(id, name) VALUES(2, "4");
INSERT INTO `catalog_packagings`(id, name) VALUES(3, "6");
INSERT INTO `catalog_packagings`(id, name) VALUES(4, "12");
INSERT INTO `catalog_packagings`(id, name) VALUES(5, "24");
INSERT INTO `catalog_packagings`(id, name) VALUES(6, "8");
INSERT INTO `catalog_packagings`(id, name) VALUES(7, "15");
INSERT INTO `catalog_packagings`(id, name) VALUES(8, "20");
INSERT INTO `catalog_packagings`(id, name) VALUES(9, "30");
INSERT INTO `catalog_packagings`(id, name) VALUES(10, "2");
INSERT INTO `catalog_packagings`(id, name) VALUES(11, "10");
INSERT INTO `catalog_packagings`(id, name) VALUES(12, "34");
INSERT INTO `catalog_packagings`(id, name) VALUES(13, "50");
INSERT INTO `catalog_packagings`(id, name) VALUES(14, "80");
INSERT INTO `catalog_packagings`(id, name) VALUES(15, "200");
INSERT INTO `catalog_packagings`(id, name) VALUES(16, "210");
INSERT INTO `catalog_packagings`(id, name) VALUES(17, "250");

/* Insert packaging volumes */
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(1, "500ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(2, "450ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(3, "330ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(4, "341ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(5, "355ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(6, "440ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(7, "473ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(8, "200ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(9, "375ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(10, "750ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(11, "1L");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(12, "1.14L");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(13, "1.75L");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(14, "7in");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(15, "13in");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(16, "100gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(17, "120gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(18, "125gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(19, "300gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(20, "425gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(21, "450gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(22, "regular");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(23, "227gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(24, "family");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(25, "party");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(26, "75gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(27, "80gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(28, "200gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(29, "275gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(30, "31gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(31, "710ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(32, "900ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(33, "960ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(34, "2L");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(35, "20oz");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(36, "32oz");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(37, "64oz");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(38, "100ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(39, "250ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(40, "7.5oz");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(41, "5.95lb");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(42, "4.5in");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(43, "30oz");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(44, "15oz");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(45, "4in");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(46, "9in");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(47, "2oz");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(48, "35ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(49, "6in");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(50, "20gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(51, "18oz");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(52, "combo");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(53, "5mm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(54, "2.5in");