use homit;

/* Insert super categories */
INSERT INTO `catalog_super_categories`(id, name, display_name, image) VALUES(1 ,"safeway" ,"Snack Vendor" ,"snack-vendor_icon.jpeg");
INSERT INTO `catalog_super_categories`(id, name, display_name, image) VALUES(2 ,"liquor-station" ,"Liquor Station" ,"liquor-station_icon.jpeg");
INSERT INTO `catalog_super_categories`(id, name, display_name, image) VALUES(3 ,"convenience" ,"Snack Vendor" ,"snack-vendor_icon.jpeg");
INSERT INTO `catalog_super_categories`(id, name, display_name, image) VALUES(4 ,"homitcar" ,"Snack Vendor" ,"snack-vendor_icon.jpeg");

/* Insert stores */
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (1, "Liquor Depot", "3630 Brentwood Rd NW, Calgary, AB T2L 1K8", "51.0869109", "-114.1277174", "2", "10:00:00", "23:59:59", "00:00:00", "02:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (2, "Liquor Depot", "5032 16 Ave NW, Calgary, AB T3B 0N3", "51.0741680999999", "-114.1652687", "2", "10:00:00", "23:59:59", "00:00:00", "02:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (3, "Liquor Depot", "5005 Dalhousie Dr NW, Calgary, AB T3A 1B2", "51.1054065999999", "-114.1616697", "2", "10:00:00", "23:59:59", "00:00:00", "02:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (4, "Liquor Depot", "1810 14 Ave NW, Calgary, AB T2N 1M7", "51.066099", "-114.10225", "2", "10:00:00", "23:59:59", "00:00:00", "02:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (5, "Liquor Depot", "831 Edmonton Trail NE, Calgary, AB T2E 3J8", "51.0595663999999", "-114.054754099999", "2", "10:00:00", "23:59:59", "00:00:00", "02:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (6, "Liquor Depot", "550 64 Ave NE, Calgary, AB, T2K 6A9", "51.111396", "-114.055103799999", "2", "10:00:00", "23:59:59", "00:00:00", "02:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (7, "Safeway Brentwood", "3636 Brentwood Rd NW, Calgary, AB T2L 1K8", "51.0853289999999", "-114.124191", "1", "08:00:00", "23:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (8, "Safeway MarketMall", "3625 Shaganappi Trail NW, Calgary, AB T3A 0E2", "51.0846392", "-114.155410099999", "1", "08:00:00", "23:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (9, "Safeway Montgomery", "5048 16 Ave NW, Calgary, AB T3B 0N3", "51.0749250999999", "-114.1660517", "1", "08:00:00", "23:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (10, "Safeway NorthHill", "1632 14 Avenue NW, Calgary, AB T2N 1M7", "51.066206", "-114.1012165", "1", "08:00:00", "23:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (11, "Safeway Sunnyside", "410 10 St NW, Calgary, AB T2N 1V9", "51.0561809", "-114.085240199999", "1", "08:00:00", "23:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (12, "Safeway Beacon Heights", "1818 Centre Street NE, 20, Calgary, AB T2P2S6", "51.0683476", "-114.0611207", "1", "08:00:00", "23:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (13, "Safeway Thorncliffe", "5607 4 St NW, Calgary, AB T2K 1B3", "51.1018284", "-114.072880699999", "1", "08:00:00", "23:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (14, "Safeway Dalhousie", "5005 Dalhousie Drive NW, Calgary, AB T3A5R8", "51.1054065999999", "-114.1616697", "1", "08:00:00", "23:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (15, "7-eleven", "6306 Bowness Rd NW, Calgary, AB T3B 0E5", "51.0852777", "-114.1781356", "3", "00:00:00", "23:59:59", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (16, "7-eleven", "4444 16 Ave NW, Calgary, AB T3B 0M4", "51.0690215", "-114.1587322", "3", "00:00:00", "00:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (17, "7-eleven", "2604 Kensington Rd NW, Calgary, AB T2N 3S5", "51.052756", "-114.120581599999", "3", "00:00:00", "00:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (18, "7-eleven", "311 16 Ave NE, Calgary, AB T2E 1K1", "51.0665286", "-114.0569338", "3", "00:00:00", "00:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (19, "7-eleven", "402 20 Ave NE, Calgary, AB T2E 1R2", "51.071005", "-114.0558704", "3", "00:00:00", "00:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (20, "7-eleven", "2417 4 St NW, Calgary, AB T2M 2Z8", "51.0739572", "-114.0720764", "3", "00:00:00", "00:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (21, "7-eleven", "4105 4 St NW, Calgary, AB T2K 1A3", "51.0879057", "-114.072426", "3", "00:00:00", "00:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (22, "7-eleven", "5003 Centre St NW, Calgary, AB T2K 0S9", "51.0963169", "-114.062861", "3", "00:00:00", "00:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (23, "7-eleven", "920 Northmount Dr NW, Calgary, AB T2L 0A9", "51.086695", "-114.103784", "3", "00:00:00", "00:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (24, "7-eleven", "1339 Northmount Dr NW, Calgary, AB T2L 0C9", "51.0926441", "-114.1287754", "3", "00:00:00", "00:00:00", "00:00:00", "00:00:00");
INSERT INTO `catalog_stores` (id, name, address, address_latitude, address_longitude, store_type, open_time, close_time, open_time_next, close_time_next) VALUES (25, "7-eleven", "4615 Valiant Dr NW, Calgary, AB T3A 0Y2", "51.0903989", "-114.1537538", "3", "00:00:00", "00:00:00", "00:00:00", "00:00:00");

/* Insert categories */
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(1, "beer", "Beer", 2);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(2, "wine", "Wine", 2);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(3, "spirit", "Spirit", 2);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(4, "liqueur", "Liqueur", 2);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(5, "snack", "Snack", 1);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(6, "snack", "Snack", 3);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(7, "bevarage", "Bevarage", 1);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(8, "bevarage", "Bevarage", 3);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(9, "party-supply", "Party-supply", 1);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(10, "party-supply", "Party-supply", 3);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(11, "bevarage", "Bevarage", 4);
INSERT INTO `catalog_categories`(id,name,display_name, super_category_id) VALUES(12, "party-supply", "Party-supply", 4);

/* Insert subcategories*/
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(1, "Lager", 1);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(2, "Witbier", 1);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(3, "Pilsner", 1);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(4, "Ale", 1);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(5, "Cider", 1);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(6, "IPA", 1);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(7, "Irish Dry Stout", 1);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(8, "White Wine", 2);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(9, "Red Wine", 2);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(10, "Sparkling Wine", 2);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(11, "Sake", 2);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(12, "Fortified wine", 2);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(13, "Rose Wine", 2);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(14, "Vodka", 3);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(15, "Whiskey", 3);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(16, "Tequila", 3);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(17, "Brandy", 3);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(18, "Rum", 3);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(19, "Gin", 3);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(20, "Cream", 4);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(21, "Fruit", 4);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(22, "Blended", 4);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(23, "Coffee", 4);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(24, "Cream", 4);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(25, "Herbal", 4);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(26, "Chips", 5);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(27, "Popcorn & Pretzel", 5);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(28, "Dried Meat", 5);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(29, "Nut Mix", 5);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(30, "Chips", 6);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(31, "Popcorn & Pretzel", 6);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(32, "Dried Meat", 6);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(33, "Nut Mix", 6);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(34, "Soda & Juice", 7);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(35, "Water & Ice", 7);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(36, "Energy Drink", 7);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(37, "Soda & Juice", 8);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(38, "Water & Ice", 8);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(39, "Energy Drink", 8);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(40, "Soda & Juice", 11);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(41, "Plastic & Paper", 9);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(42, "Games & Décor", 9);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(43, "Barware", 9);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(44, "Plastic & Paper", 10);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(45, "Games & Décor", 10);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(46, "Barware", 10);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(47, "Plastic & Paper", 12);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(48, "Games & Décor", 12);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(49, "Barware", 12);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(50, "Confectionery", 5);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(51, "Confectionery", 6);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(52, "Sauce & Seasoning", 5);
INSERT INTO `catalog_subcategories`(id,name,category_id) VALUES(53, "Sauce & Seasoning", 6);

/* Insert types */
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(1, "Pale Lager", 1);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(2, "Wheat Ale", 2);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(3, "Dortmunder", 1);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(4, "Brown Ale", 4);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(5, "Kristalweizen", 4);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(6, "Dark Lager", 1);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(7, "Czech Style", 3);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(8, "Hard Cider", 5);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(9, "India Pale Ale", 6);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(10, "Adjunct Lager ", 1);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(11, "Light Lager", 1);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(12, "Fruit Beer", 1);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(13, "German Pilsner", 3);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(14, "Amber Lager", 1);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(15, "Cream Ale", 4);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(16, "Pale Ale", 4);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(17, "American IPA", 6);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(18, "Scottish Style", 4);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(19, "English Pale Ale", 6);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(20, "Japanese Rice Lager", 1);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(21, "Amber Ale", 4);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(22, "Original Cider", 5);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(23, "Fruit Cider", 5);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(24, "Flower Cider", 5);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(25, "Irish Style", 7);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(26, "American Lager", 1);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(27, "Danish Style", 5);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(28, "Pinot Grigio", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(29, "Cabernet Sauvignon", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(30, "Shiraz", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(31, "Cabernet Merlot", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(32, "Sauvignon Blanc", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(33, "Merlot", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(34, "Moscato", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(35, "Chardonnay", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(36, "Rose", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(37, "Champagne", 10);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(38, "Big Bang Theory", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(39, "Hatfield's Fuse", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(40, "Smooth White", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(41, "Pinot Noir", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(42, "Riesling", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(43, "Malbec", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(44, "Ice Wine", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(45, "Red Blend", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(46, "White Blend", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(47, "Inferno", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(48, "Syrah", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(49, "Pink Moscato", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(50, "Zinfandel", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(51, "White Zinfandel", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(52, "Sake", 11);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(53, "Vermouth", 12);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(54, "Aperitif Wine", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(55, "Viognier", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(56, "Sparkling Red", 10);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(57, "Chianti", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(58, "Blend", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(59, "Corvina", 9);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(60, "Prosecco", 10);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(61, "Pinot Noir Rose", 8);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(62, "Sherry", 12);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(63, "Flavorless Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(64, "Peach Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(65, "Vanilla Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(66, "Lime Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(67, "Mandarin Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(68, "Cytrus Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(69, "Lemon Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(70, "Lemon & Lime Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(71, "Cherry Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(72, "Grape Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(73, "Green Apple Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(74, "Orange Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(75, "Malt Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(76, "Raspberry Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(77, "Blueberry Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(78, "Pineapple Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(79, "Red Berry Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(80, "Tropical Vodka", 14);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(81, "Bourbon", 15);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(82, "Rye", 15);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(83, "Blended", 15);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(84, "Irish", 15);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(85, "Scotch", 15);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(86, "Oaked", 15);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(87, "Single Malt", 15);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(88, "Irish Cream", 15);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(89, "Reposado Tequila", 16);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(90, "Gold Tequila", 16);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(91, "Silver Tequila", 16);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(92, "Anejo Tequila", 16);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(93, "Lime Tequila", 16);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(94, "Cognac", 17);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(95, "Spiced Rum", 18);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(96, "Black Spiced Rum", 18);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(97, "White Rum", 18);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(98, "Gold Rum", 18);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(99, "Dry Gin", 19);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(100, "Irish Liqueur", 20);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(101, "Apple Liqueur", 21);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(102, "Grape Liqueur", 21);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(103, "Raspberry Liqueur", 21);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(104, "Watermelon Liqueur", 21);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(105, "Hezelnut Liqueur", 25);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(106, "Blended Liqueur", 22);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(107, "Black Raspberry Liqueur", 21);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(108, "Coffee Liqueur", 23);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(109, "Cream Liqueur", 20);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(110, "Fruit Liqueur", 21);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(111, "Herbal Liqueur", 25);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(112, "Infused Wine", 21);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(113, "Classic Chips", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(114, "Sour Cream & Onion Chips", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(115, "Cheddar Cheese Chips", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(116, "Barbecue Chips", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(117, "Cheesy Chips", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(118, "Cheddar Jalapeno", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(119, "Salt & Vinegar Chips", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(120, "Cheese & Onion Popcorn", 27);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(121, "White Cheddar Popcorn", 27);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(122, "Cheddar Jalapeno Popcorn", 27);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(123, "Beef Jerky", 28);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(124, "Pork Jerky", 28);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(125, "Chicken Jerky", 28);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(126, "All Dressed Chips", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(127, "Cheesy Nachos", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(128, "Double Cheesy Nachos", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(129, "Tortilla Chips", 26);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(130, "Spicy Pistachos", 29);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(131, "Salty Pistachos", 29);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(132, "Roasted Pistachos", 29);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(133, "Peanut", 29);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(134, "Classic Chips", 30);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(135, "Sour Cream & Onion Chips", 30);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(136, "Cheddar Cheese Chips", 30);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(137, "Barbecue Chips", 30);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(138, "Cheesy Chips", 30);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(139, "Cheddar Jalapeno", 30);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(140, "Salt & Vinegar Chips", 30);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(141, "Cheese & Onion Popcorn", 31);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(142, "White Cheddar Popcorn", 31);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(143, "Cheddar Jalapeno Popcorn", 31);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(144, "Beef Jerky", 32);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(145, "Pork Jerky", 32);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(146, "Chicken Jerky", 32);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(147, "All Dressed Chips", 30);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(148, "Cheesy Nachos", 30);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(149, "Double Cheesy Nachos", 30);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(150, "Tortilla Chips", 30);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(151, "Spicy Pistachos", 33);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(152, "Salty Pistachos", 33);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(153, "Roasted Pistachos", 33);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(154, "Peanut", 33);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(155, "Classic Soda", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(156, "Diet Soda", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(157, "Ginger Ale Soda", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(158, "Classic Water", 35);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(159, "Raspberry Limonade", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(160, "Orange Limonade", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(161, "Tonic Water", 35);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(162, "Cranberry Juice", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(163, "Classic Clamato", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(164, "Spicy Clamato", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(165, "Lemon Juice", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(166, "Lime Juice", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(167, "Blend Juice", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(168, "Pineapple Juice", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(169, "Mango Juice", 34);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(170, "Diet Energy Drink", 36);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(171, "Classic Energy Drink", 36);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(172, "Ice", 35);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(173, "Classic Soda", 37);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(174, "Diet Soda", 37);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(175, "Ginger Ale Soda", 37);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(176, "Classic Water", 38);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(177, "Raspberry Limonade", 37);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(178, "Orange Limonade", 37);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(179, "Tonic Water", 38);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(180, "Cranberry Juice", 37);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(181, "Classic Clamato", 37);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(182, "Spicy Clamato", 37);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(183, "Lemon Juice", 37);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(184, "Lime Juice", 37);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(185, "Blend Juice", 37);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(186, "Pineapple Juice", 37);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(187, "Mango Juice", 37);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(188, "Diet Energy Drink", 39);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(189, "Classic Energy Drink", 39);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(190, "Ice", 38);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(191, "Lemon Juice", 40);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(192, "Lime Juice", 40);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(193, "Plastic Cup", 47);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(194, "Candle", 42);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(195, "Classic Beer Opener", 49);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(196, "Bottle Opener", 49);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(197, "Plastic Plate", 47);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(198, "5mm Flexible Straw", 47);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(199, "20 oz Plastic Shot", 47);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(200, "Heavy Weight Plastic Cutlery Set 40x20x20", 47);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(201, "Plastic Fork", 47);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(202, "Plastic Teaspoon", 47);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(203, "Plastic Knives", 47);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(204, "Free Flow Metal Liquor Pourer", 49);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(205, "30oz Coctail Shaker", 49);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(206, "Classic Shape 15oz Wine Glass", 49);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(207, "152mm Paddle Skewer", 49);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(208, "2-ply Facial Tissue Napkin", 47);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(209, "Wooden Toothpicks", 49);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(210, "2-ply Paper Towel", 41);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(211, "Classic Chocolate ", 50);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(212, "Hazelnut Chocolate ", 50);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(213, "White Chocolate", 50);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(214, "Cookies & Cream Chocolate", 50);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(215, "Dark Chocolate", 50);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(216, "Classic Chocolate ", 51);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(217, "Hazelnut Chocolate ", 51);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(218, "White Chocolate", 51);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(219, "Cookies & Cream Chocolate", 51);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(220, "Dark Chocolate", 51);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(221, "Ranch Dip", 52);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(222, "Red Pepper Salsa", 52);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(223, "Garlic Salsa", 52);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(224, "Spinach Dip", 52);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(225, "Spicy Salsa", 52);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(226, "Ranch Dip", 53);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(227, "Red Pepper Salsa", 53);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(228, "Garlic Salsa", 53);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(229, "Spinach Dip", 53);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(230, "Spicy Salsa", 53);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(231, "Classic Sparkling Water", 35);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(232, "Lemon & Orange Sparkling Water", 35);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(233, "Classic Sparkling Water", 38);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(234, "Lemon & Orange Sparkling Water", 38);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(235, "Red Playing Cards", 48);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(236, "Table Tennis Balls", 48);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(237, "Strawberry Twizzler", 50);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(238, "Strawberry Twizzler", 51);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(239, "Salt & Vinegar Seasoning", 52);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(240, "Ketchup Seasoning", 52);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(241, "White Cheddar Seasoning", 52);
INSERT INTO `catalog_types`(id,name,subcategory_id) VALUES(242, "Popcorn Bags", 27);

/* Insert packaging types */
INSERT INTO `catalog_containers`(id, name) VALUES(1, "bottle");
INSERT INTO `catalog_containers`(id, name) VALUES(2, "can");
INSERT INTO `catalog_containers`(id, name) VALUES(3, "keg");
INSERT INTO `catalog_containers`(id, name) VALUES(4, "box");
INSERT INTO `catalog_containers`(id, name) VALUES(5, "pack");
INSERT INTO `catalog_containers`(id, name) VALUES(6, "jar");
INSERT INTO `catalog_containers`(id, name) VALUES(7, "object");
INSERT INTO `catalog_containers`(id, name) VALUES(8, "bar");

/* Insert packagings */
INSERT INTO `catalog_packagings`(id, name) VALUES(1, "1");
INSERT INTO `catalog_packagings`(id, name) VALUES(2, "2");
INSERT INTO `catalog_packagings`(id, name) VALUES(3, "4");
INSERT INTO `catalog_packagings`(id, name) VALUES(4, "6");
INSERT INTO `catalog_packagings`(id, name) VALUES(5, "8");
INSERT INTO `catalog_packagings`(id, name) VALUES(6, "12");
INSERT INTO `catalog_packagings`(id, name) VALUES(7, "15");
INSERT INTO `catalog_packagings`(id, name) VALUES(8, "18");
INSERT INTO `catalog_packagings`(id, name) VALUES(9, "20");
INSERT INTO `catalog_packagings`(id, name) VALUES(10, "24");
INSERT INTO `catalog_packagings`(id, name) VALUES(11, "30");
INSERT INTO `catalog_packagings`(id, name) VALUES(12, "34");
INSERT INTO `catalog_packagings`(id, name) VALUES(13, "50");
INSERT INTO `catalog_packagings`(id, name) VALUES(14, "80");
INSERT INTO `catalog_packagings`(id, name) VALUES(15, "200");
INSERT INTO `catalog_packagings`(id, name) VALUES(16, "210");
INSERT INTO `catalog_packagings`(id, name) VALUES(17, "250");

/* Insert packaging volumes */
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(1, "100ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(2, "200ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(3, "250ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(4, "330ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(5, "341ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(6, "355ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(7, "375ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(8, "440ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(9, "450ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(10, "473ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(11, "500ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(12, "550ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(13, "710ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(14, "750ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(15, "900ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(16, "960ml");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(17, "1L");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(18, "1.14L");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(19, "1.75L");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(20, "2L");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(21, "2oz");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(22, "7.5oz");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(23, "8oz");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(24, "15oz");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(25, "18oz");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(26, "20oz");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(27, "30oz");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(28, "32oz");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(29, "64oz");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(30, "5.95lb");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(31, "20gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(32, "31gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(33, "75gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(34, "80gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(35, "100gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(36, "125gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(37, "200gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(38, "227gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(39, "275gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(40, "425gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(41, "450gm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(42, "regular");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(43, "family");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(44, "party");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(45, "combo");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(46, "5mm");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(47, "2.5in");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(48, "4.5in");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(49, "6in");
INSERT INTO `catalog_packaging_volumes`(id, volume_name) VALUES(50, "7in");