use homit;

/*Store Type*/
INSERT INTO `catalog_store_types`(id, name, display_name, api_name, image) VALUES(6,"linas-italian-market", "Lina's Italian Market", "linas-italian-market", "linas-italian-store_icon.png");

/*Store Type*/
INSERT INTO `catalog_stores` (id, id_prefix, name, address, address_latitude, address_longitude, phone_number, store_type) VALUES (335, "s_", "Lina's Italian Market", "2202 Centre St NE, Calgary, AB T2E 2T5", "51.071908", "-114.062205", "4032779166", "6");

/* Insert Store - Hours */
INSERT INTO `stores_hours` (store_id, day, open_time, close_time) VALUES (335, 1, "07:59:59", "18:59:59");
INSERT INTO `stores_hours` (store_id, day, open_time, close_time) VALUES (335, 2, "07:59:59", "18:59:59");
INSERT INTO `stores_hours` (store_id, day, open_time, close_time) VALUES (335, 3, "07:59:59", "18:59:59");
INSERT INTO `stores_hours` (store_id, day, open_time, close_time) VALUES (335, 4, "07:59:59", "18:59:59");
INSERT INTO `stores_hours` (store_id, day, open_time, close_time) VALUES (335, 5, "07:59:59", "18:59:59");
INSERT INTO `stores_hours` (store_id, day, open_time, close_time) VALUES (335, 6, "07:59:59", "18:59:59");
INSERT INTO `stores_hours` (store_id, day, open_time, close_time) VALUES (335, 7, "07:59:59", "17:59:59");

/*Catalog Description*/
INSERT INTO `catalog_description_names`(id, name) VALUES(6, "ingredients");
INSERT INTO `catalog_description_names`(id, name) VALUES(7, "serving_suggestions");

/*Catalog - Categories*/
INSERT INTO `catalog_categories` (id, name, display_name) VALUES(9, "pasta-and-baking", "Pasta and Baking");
INSERT INTO `catalog_categories` (id, name, display_name) VALUES(10, "canned-and-jarred", "Canned and Jarred");
INSERT INTO `catalog_categories` (id, name, display_name) VALUES(11, "grains-and-legumes", "Grains and Legumes");
INSERT INTO `catalog_categories` (id, name, display_name) VALUES(12, "herbs-and-spices", "Herbs and Spices");
INSERT INTO `catalog_categories` (id, name, display_name) VALUES(13, "dry-packaged", "Dry Packaged");
INSERT INTO `catalog_categories` (id, name, display_name) VALUES(14, "condiments", "Condiments");
INSERT INTO `catalog_categories` (id, name, display_name) VALUES(15, "baked-goods", "Baked Goods");
INSERT INTO `catalog_categories` (id, name, display_name) VALUES(16, "oil-and-vinegar", "Oil and Vinegar");
INSERT INTO `catalog_categories` (id, name, display_name) VALUES(17, "coffee-and-tea", "Coffee and Tea");
INSERT INTO `catalog_categories` (id, name, display_name) VALUES(18, "confectionery", "Confectionery");

/*Catalog - Subcategories*/
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(37, "Pasta", "9");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(38, "Beans", "10");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(39, "Rice", "11");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(40, "Bouillon Mix", "12");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(41, "Soup & Potatoes", "13");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(42, "Soup", "10");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(43, "Mixed Seasonings", "12");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(44, "Fish & Seafood", "10");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(45, "Bread Crumbs", "9");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(46, "Salt & Pepper", "12");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(47, "Whole Spices", "12");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(48, "Rubbed Spices", "12");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(49, "Seed Spices", "12");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(50, "Spice Powder", "12");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(51, "Chopped Spices", "12");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(52, "Spice Rub", "12");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(53, "Pizza Sauce", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(54, "Hot Sauce", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(55, "Horseradish", "10");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(56, "Horseradish & Mustard", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(57, "Smoke & BBQ", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(58, "Extra Hot Sauce", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(59, "Worcestershire Sauce", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(60, "Lemon Sauce", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(61, "Garlic Sauce", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(62, "Mixed Sauce", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(63, "Mayonnaise Based", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(64, "Pesto & Spread", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(65, "Ketchup", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(66, "Peppers", "10");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(67, "Salsa", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(68, "Pasta Sauce", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(69, "Tomatoes", "10");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(70, "Cooking Sauce", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(71, "Crackers & Flatbread", "5");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(72, "Salmas & Salmitas", "5");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(73, "Whole Wheat Bread", "15");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(74, "Breadsticks", "15");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(75, "Taralli", "15");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(76, "Garlic & Beets", "10");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(77, "Antipasto", "10");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(78, "Food Toppings", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(79, "Olives", "10");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(80, "Mushrooms", "10");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(81, "Eggplants & Zucchini", "10");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(82, "Asparagus & Onions", "10");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(83, "Capers & Caperberries", "10");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(84, "Artichokes", "10");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(85, "Cucumber", "10");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(86, "Classic Olive Oil", "16");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(87, "Basil Flavored", "16");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(88, "Garlic Flavored", "16");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(89, "Piccante Flavored", "16");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(90, "Mixed Flavors", "16");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(91, "Pizza Flavored", "16");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(92, "Rosemary Flavored", "16");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(93, "Bruschetta Flavored", "16");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(94, "Seed & Nut Oil", "16");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(95, "Fruit Oil", "16");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(96, "Hot Olive Oil", "16");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(97, "Juice", "6");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(98, "Dark Balsamic Vinegar", "16");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(99, "White Balsamic Vinegar", "16");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(100, "Fruit Flavored Vinegar", "16");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(101, "White Glaze", "9");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(102, "Balsamic Glaze", "16");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(103, "Olive Oil Spray", "16");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(104, "Oil Spray", "16");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(105, "Classic Glaze", "9");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(106, "Chips", "5");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(107, "Syrup", "6");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(108, "Ice Tea", "6");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(109, "Lemonade", "6");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(110, "Cocktail Mix", "6");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(111, "Sparkling Juice", "6");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(112, "Nutritional Mix", "6");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(113, "Soda & Water", "6");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(114, "Beer", "6");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(115, "Medium Roast Coffee", "17");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(116, "Dark Roast Coffee", "17");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(117, "Espresso", "17");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(118, "Blend Roast Coffee", "17");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(119, "Black Tea", "17");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(120, "White Tea", "17");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(121, "Green Tea", "17");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(122, "Pizza Flour", "9");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(123, "Fruit Spread", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(124, "Chocolate Spread", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(125, "Nuts", "10");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(126, "Jam", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(127, "Honey", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(128, "Mostarda & Molasses", "14");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(129, "Truffle & Candy", "18");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(130, "Chocolate Bar", "18");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(131, "Cookies & Wafers", "18");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(132, "Cakes & Biscuits", "18");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(133, "Mixed Pasta", "9");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(134, "Macaroni", "9");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(135, "Lasagne & Spaghetti", "9");
INSERT INTO `catalog_subcategories` (id, name, category_id) VALUES(136, "Fish & Seafood", "13");


/*Catalog - Types*/
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(207, "Rigate Pasta", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(208, "Fusilli Pasta", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(209, "Orecchiette Pasta", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(210, "Linguine Pasta", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(211, "Rigatone Pasta", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(212, "Lasagne Pasta", "135");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(213, "Brine Marinated Beans", "38");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(214, "Lupinus Genus Seeds", "38");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(215, "Green Beans", "38");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(216, "Mixed Beans", "38");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(217, "Chickpea Canned", "38");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(218, "Red Beans", "38");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(219, "Yellow Lentils", "38");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(220, "Black Beans", "38");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(221, "Borlotti Beans", "38");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(222, "Green Lentils", "38");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(223, "Egyptian Style Beans", "38");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(224, "Cannellini Beans", "38");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(225, "Romano Beans", "38");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(226, "Lima Beans", "38");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(227, "White Beans", "38");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(228, "Pinto Beans", "38");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(229, "Faba Beans", "38");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(230, "Carnolini Rice", "39");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(231, "Carnaroli Rice", "39");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(232, "Italian Rice", "39");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(233, "Arborio Rice", "39");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(234, "Durum Wheat Semolina Balls", "39");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(235, "Mix Flavors Herbs Bouillon", "40");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(236, "Chicken Bouillon", "40");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(237, "Beef Bouillon", "40");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(238, "Mushrooms Bouillon", "40");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(239, "Fish Bouillon", "40");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(240, "Basil and Garlic Bouillon", "40");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(241, "Spelt Soup Dehydrated", "41");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(242, "Mushed Potatoes Dehydrated", "41");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(243, "Lentil Soup", "42");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(244, "Bean Soup", "42");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(245, "Minestrone Soup", "42");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(246, "Leek Soup", "42");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(247, "Seafood Soup", "42");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(248, "French Onion Soup", "42");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(249, "Mixed Herb Seasoning", "43");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(250, "Red Pepper Soup", "42");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(251, "Green Pea Dehydrated", "41");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(252, "Chickpea Dehydrated", "41");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(253, "Mix Vegetables Bouillon", "40");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(254, "Carrot Soup", "42");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(255, "Tuna in Olive Oil", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(256, "Octopus in Marinade Sauce", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(257, "Sardines in Tomtato Sauce", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(258, "Cod Fish in Biscaye Sauce", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(259, "Squid in Ragout Sauce", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(260, "Mackerels in Olive Oil", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(261, "Calmars in Hot Sauce", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(262, "Sardines in Soybean Oil", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(263, "Sardines in Olive Oil", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(264, "Mexican Style Tuna Salad", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(265, "Mussels in Galician Sauce", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(266, "Sardines in Vegetable Oil", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(267, "Tuna in Soybean Oil", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(268, "Light Tuna", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(269, "Tuna in Spring Water", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(270, "Yellowfin Tuna in Olive Oil", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(271, "Herring in Paprika Sauce", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(272, "Herring in Horseradish Sauce", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(273, "Herring in Tomato Sauce", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(274, "Herring in Wine Sauce", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(275, "Sprats in Oil", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(276, "Mackerel in White Wine", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(277, "Mackerel with Mustard", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(278, "Grilled Mackerel", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(279, "Claims in Water", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(280, "Pink Salmon", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(281, "Snails in Water", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(282, "Escargots in Water", "44");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(283, "Smoked Salmon", "136");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(284, "Wheat Crumbs", "45");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(285, "Flavored Wheat Crumbs", "45");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(286, "Siracha Salt", "46");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(287, "Lemon and Pepper", "46");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(288, "Peppercorns", "46");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(289, "Cloves Whole", "47");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(290, "Dill Weed Rubbed", "48");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(291, "Fennel Seeds", "49");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(292, "Spice Powder", "50");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(293, "Curing Salt", "46");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(294, "Dehydrated Bay Leaves", "47");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(295, "Basil Rubbed", "48");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(296, "Anise Seeds", "49");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(297, "Whole Flower", "47");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(298, "Allspice Ground", "50");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(299, "Whole Sticks", "47");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(300, "Cayenne Pepper", "46");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(301, "Hirb Flakes", "48");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(302, "Rubbed Spice", "48");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(303, "Powder", "50");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(304, "Whole Leaves", "47");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(305, "Mixed Seasoning", "43");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(306, "Whole Fruits", "47");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(307, "Coarse Grind", "46");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(308, "Whole Twigs", "47");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(309, "Seaspnong Salt", "46");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(310, "Fine Grind", "46");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(311, "Spice Seeds", "49");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(312, "Sea Salt", "46");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(313, "Pink Himalayan Salt", "46");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(314, "Chopped Garlic", "51");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(315, "Chopped Chili", "51");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(316, "Cajun Rub ", "52");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(317, "Blackening", "52");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(318, "Lemon Herb", "52");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(319, "Salmon Rub", "52");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(320, "Steak Rub", "52");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(321, "Fish Rub", "52");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(322, "Rib Rub", "52");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(323, "Classic Pizza Sauce", "53");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(324, "Hot Sauce Piquan", "54");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(325, "Jerk Sauce", "54");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(326, "Pepper Sauce", "54");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(327, "Extra Hot Jarred Product", "55");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(328, "Horseradish Sauce", "56");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(329, "Mesquite Sauce", "57");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(330, "Blazin' Saddle Sauce", "58");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(331, "Texas Champagne Sauce", "54");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(332, "Canadian Hot Sauce", "54");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(333, "Worcestershire Sauce", "59");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(334, "Hot Sauce", "54");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(335, "Mixed Sauce", "60");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(336, "PERI-PERI Sauce", "54");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(337, "Louisiana's Pure Sauce", "54");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(338, "Chipotle Sauce", "54");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(339, "Extra Hot Sauce", "58");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(340, "Chicken BBQ Sauce", "57");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(341, "Hot BBQ Sauce", "57");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(342, "Aioli Sauce", "60");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(343, "Tartar Sauce", "63");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(344, "Hot Mustard Condiment", "56");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(345, "Mild Mustard Condiment", "56");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(346, "Garlic Spread", "64");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(347, "Remoulade Sauce", "63");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(348, "Mayonnaise", "63");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(349, "Mustard Condiment", "56");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(350, "Fritessaus", "63");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(351, "Knoflook Sauce", "63");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(352, "Curry Barbecue Sauce", "65");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(353, "Curry Sauce", "65");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(354, "Paprika Pesto", "64");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(355, "Lemon Pesto", "64");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(356, "Spicy Black Olive Tapenade", "64");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(357, "Pesto Sauce", "64");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(358, "Red Pesto Rouge", "64");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(359, "Tomato Pesto", "64");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(360, "Balzamic Pesto", "64");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(361, "Hot Pepper Rings", "66");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(362, "Hot Spread", "64");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(363, "Medium Hot Salsa", "67");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(364, "Fruit Salsa", "67");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(365, "Extra Hot Salsa", "67");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(366, "Red Pepper Sauce", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(367, "Puttanesca  Sauce", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(368, "Alfredo Sauce", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(369, "Olive Flavored Sauce", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(370, "Gorgonzola Sauce", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(371, "Five Cheese Sauce", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(372, "Vodka Sauce", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(373, "Mushrooms Sauce", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(374, "Bolognese Meat Sauce", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(375, "Hot Pepper", "64");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(376, "Truffle Pesto", "64");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(377, "Strained Tomatoes", "69");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(378, "Strained with Basil Tomatoes", "69");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(379, "Arrabbiata Sauce", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(380, "Classic Pasta Sauce", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(381, "Tomatoe Puree", "69");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(382, "Spiced Pizza Sauce", "53");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(383, "Pizza Sauce With Herbs", "53");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(384, "Lemon & Chicken Cooking Sauce", "70");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(385, "Classic Salsa", "67");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(386, "Roasted Garlic Sauce", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(387, "Marinara Sauce", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(388, "Pasta Sauce With Artichoke", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(389, "Hot Pasta Sauce", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(390, "Peeled Tomatoes", "69");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(391, "Diced Tomatoes", "69");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(392, "Crushed & Strained Tomatoes", "69");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(393, "Porici Sauce", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(394, "Cuttlefish Black Ink Sauce", "70");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(395, "Cherry Toamato Cooking Sauce", "70");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(396, "Pasta Sauce with Basil", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(397, "Spicy Pasta Sauce", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(398, "Olive and Caper Pasta", "68");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(399, "Cheese Flavored Twists", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(400, "Cheese & Garlic Twists", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(401, "Rosemary Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(402, "Fig and Olive Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(403, "Cranberry and Hazelnut Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(404, "Beet and Balsamic Flatbreads", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(405, "Kale and English Walnut Flatbreads", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(406, "Baguette Crisps", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(407, "Cheese Flavored Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(408, "Roasted Garlic Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(409, "Mixed Flavors Flatbreads", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(410, "Classic Salmitas", "72");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(411, "Classic Salmas", "72");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(412, "Salty Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(413, "Rice Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(414, "Garlic Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(415, "Organic Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(416, "Rosemary & Garlic Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(417, "Parmesan & Red Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(418, "Red Onion & Balsamic Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(419, "Original Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(420, "Bread Loafs", "73");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(421, "Rosemary Breadstick", "74");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(422, "Black Olive Breadstick", "74");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(423, "Olive Oil Breadstick", "74");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(424, "Seasame Seeds Breadstick", "74");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(425, "Cheese Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(426, "Mixed Flavors Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(427, "Tomato and Basil Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(428, "Feta and Oregano Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(429, "Olive Oil Crostini Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(430, "Rosemary Crostini Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(431, "Mushroom Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(432, "Lemon Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(433, "Mixed Seeds Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(434, "Mediterranean Style Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(435, "Rosemary & Pistachio Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(436, "Fennel Seeds Taralli", "75");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(437, "Pizza Taralli", "75");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(438, "Mediterranean Taralli", "75");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(439, "Pizza Flavored Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(440, "Olive Flavored Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(441, "Toasted Almond Thins", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(442, "Oven Baked Crackers", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(443, "Palm Oil Breadstick", "74");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(444, "Marinated Garlic", "76");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(445, "Spicy Marinated Garlic", "76");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(446, "Mediterranean Style Appetizer", "77");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(447, "Cold Pasta Topping", "78");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(448, "Pitted Olives", "79");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(449, "Cold Rice Topping", "78");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(450, "Wild Forest Mixed Mushrooms", "80");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(451, "Mild Spicy Spread", "64");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(452, "Mild Spicy Tapenade", "64");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(453, "Mixed Mushrooms", "80");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(454, "Jarred & Hot Eggplant Strips", "81");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(455, "Jarred Eggplant Strips", "81");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(456, "Jarred Wild Onions", "82");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(457, "Sweet Antipasto", "77");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(458, "Onions in Balsamic Vinegar", "82");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(459, "Cocktails Onions", "82");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(460, "Onions in Wine Vinegar", "82");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(461, "Peeled and White Asparagus", "82");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(462, "Pickled Asparagus", "82");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(463, "White Asparagus", "82");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(464, "Eggplants Grilled in Oil", "81");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(465, "Grilled in Oil", "66");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(466, "Sweet Marinated Beets", "76");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(467, "Small Size Capers", "83");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(468, "Sweet and Roasted Peppers", "66");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(469, "Hot and Pickled Peppers", "66");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(470, "Salted Capers", "83");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(471, "Capers in Vinegar", "83");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(472, "Capers Capucines", "83");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(473, "Tomatoes in Oil", "69");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(474, "Marinated Caperberries", "83");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(475, "Classic Sundried Tomaotes", "69");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(476, "Hot & Whole Peppers", "66");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(477, "Hot Peppers", "66");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(478, "Roasted Peppers", "66");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(479, "Cherry Toamatos in Oil", "69");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(480, "Sundried Cherry Toamato", "69");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(481, "Sliced Jalapeno", "66");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(482, "Marinated Green Pappers", "66");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(483, "Sundried Tomatoes in Oil", "69");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(484, "Cheese Stuffed Sweet Peppers", "66");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(485, "Calabrian Chili Peppers", "66");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(486, "Cheese Stuffed Hot Peppers", "66");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(487, "Peppers in Brine", "66");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(488, "Hot and Sliced Pepprs in Oil", "66");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(489, "Cracked Green Olives", "79");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(490, "Grilled Mushrooms in Oil", "81");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(491, "Green Olives", "79");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(492, "Bright Green Olives", "79");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(493, "Mixed Olives", "79");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(494, "Bright Red Olives", "79");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(495, "Green and Queen Size Olives", "79");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(496, "Chili Peppers", "66");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(497, "Hot Cherry Peppers", "66");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(498, "Green & Queen Size Olives", "79");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(499, "Almond Stuffed", "79");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(500, "Olives in Vinegar", "79");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(501, "Cocktail Olives", "79");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(502, "Sliced Mushroms in Oil", "80");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(503, "Whole Green and Queen Size Olives", "79");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(504, "Almond Stuffed Olives", "79");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(505, "Grilled Artichokes in Oil", "84");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(506, "Marinated Artichokes in Oil", "84");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(507, "French Style Pickled Cucumbers", "85");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(508, "Extra Fine Pickled Cucumbers", "85");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(509, "Grilled in Oil Artichokes", "84");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(510, "Sliced Olives", "79");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(511, "Deli Style Pickled Cucumbers", "85");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(512, "Marinated Artichoke Hearts", "84");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(513, "Hot Pickled Polish Cucumbers", "85");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(514, "Extra Vergin Olives", "86");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(515, "Extra Vergin Olives Oil", "90");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(516, "Walnut Oil", "94");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(517, "Infused Oil", "90");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(518, "Portuguese Extra Vergin Olives", "86");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(519, "Pure Olive Oil", "86");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(520, "Lemon Flavored Oil", "90");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(521, "Spanish Style", "86");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(522, "Pumpkin Seed Oil", "94");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(523, "Black Truffle Flavored Oil", "90");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(524, "White Truffle Flavored Oil", "90");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(525, "Pistachio Oil", "94");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(526, "Almond Oil", "94");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(527, "Avacado Oil", "95");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(528, "Hazelnut Oil", "94");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(529, "Grapeseed Oil", "94");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(530, "Coconut Oil", "95");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(531, "California Style Olive Oil", "90");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(532, "Smoke Flavor Based Oil", "90");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(533, "Smoke Flavor Based Olive Oil", "86");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(534, "Smoke Flavor Based Juice", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(535, "Dark Balsamic Vinegar of Modena", "98");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(536, "Cooked Wine Vinegar", "99");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(537, "White Balsamic Vinegar of Modena", "98");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(538, "Apple Flavored Balsamic Vinegar ", "100");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(539, "Traditional White Vinegar", "99");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(540, "Rasberry White Balsamic Vinegar", "100");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(541, "Décor Class Balsamic Vinegar", "98");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(542, "Pear Infused White Balsamic Vinegar", "99");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(543, "Mango Balsamic Vinegar", "99");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(544, "White Glaze", "101");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(545, "Fig Infused White Vinegar", "100");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(546, "Raspberry Blush White Vinegar", "100");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(547, "Cacao Balsamic Glaze", "102");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(548, "Traditional Balsamic Glaze", "102");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(549, "Fig Balsamic Glaze", "102");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(550, "Orange Balsamic Glaze", "102");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(551, "Lemon Balsamic Glaze", "102");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(552, "Wildberry Balsamic Glaze", "102");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(553, "Extra Virgin Olive Oil Spray", "104");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(554, "Grapeseed Oil Spray", "104");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(555, "Truffle Flavored Oil Spray", "104");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(556, "Garlic Flavored Oil Spray", "104");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(557, "Traditional Dark Balsamic Vinegar", "98");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(558, "Original Classic Glaze", "105");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(559, "Apple Cider Vinegar", "100");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(560, "Balsamic Vinegar of Modena Glaze", "98");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(561, "Champagne Balsamic Vinegar", "99");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(562, "Rasberry Balsamic Vinegar", "100");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(563, "Black Olive Oil", "86");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(564, "Sherry Balsamic Vinegar ", "98");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(565, "Green Olive Oil", "86");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(566, "Lemon Vinegar", "100");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(567, "Red Grape Vinegar", "100");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(568, "White Grape Vinegar", "100");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(569, "Apple Vinegar", "100");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(570, "Fig Balsamic Vinegar", "100");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(571, "Honey and Apple Balsamic Vinegar", "100");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(572, "Yuzu Rice Vinegar", "99");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(573, "Organic Apple Cider Vinegar", "100");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(574, "Rice Vinegar", "99");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(575, "Tarragon White Wine Vinegar", "99");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(576, "Barrel Aged Wine Balsamic Vinegar", "99");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(577, "Red Wine Vinegar", "100");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(578, "White Wine Vinegar", "100");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(579, "Original Falafel Chips", "106");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(580, "Balsamic Vinegar Flavoured Chips", "106");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(581, "Crunchips Paprika Chips", "106");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(582, "Salty Chips", "106");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(583, "Cheddar Biscuits", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(584, "Italian Herb Toast with Olive Oil", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(585, "Hommade Style Tortilla Chips", "106");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(586, "Garlic and Cheese Toasts", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(587, "Whole Wheat Crostini", "71");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(588, "Mild Paprika Chips", "106");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(589, "Mango Nectar Juice", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(590, "Pear Nectar Juice", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(591, "Pineapple Nectar Juice", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(592, "Tomato Juice", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(593, "Peach Nectar Juice", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(594, "Apricot Nectar Juice", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(595, "Almond Flavored Syrup", "107");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(596, "Peach Ice Tea", "108");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(597, "Half-Half Ice Tea", "108");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(598, "Mango Lemanode", "109");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(599, "Mixed Juices", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(600, "Bloody Mary Cocktail Mix", "110");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(601, "Cherry juice", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(602, "Pure Apple Juice", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(603, "Sparkling Orange Juice", "111");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(604, "Sparkling Lemon Juice", "111");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(605, "Orange and Pomegranate Sparkling Juice", "111");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(606, "Sparkling Grapefruit Juice", "111");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(607, "Cold Mocha High Nutritional Beverage", "112");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(608, "Cold Green Tea High Nutritional Beverage", "112");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(609, "Cold Vanilla Latte Nutritional Beverage", "112");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(610, "Lemon Lemonade", "109");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(611, "Sparkling Blueberry Juice", "111");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(612, "Sparkling Cranberry Juice", "111");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(613, "Sparkling Tangerine Juice", "111");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(614, "Pomegranate Juice", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(615, "Lemon Juice", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(616, "Lime Juice", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(617, "Coconut Water", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(618, "Pure Lime Juice", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(619, "Ginger Beer Carbonated Beverage", "113");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(620, "Root Beer Carbonated Beverage", "113");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(621, "Spring Soda Water", "113");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(622, "Tonic Cocktail Mix", "110");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(623, "Pure Maple Syrup", "107");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(624, "Pure Mango Juice", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(625, "Apple Juice", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(626, "Orange Juice", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(627, "Lemon Water", "113");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(628, "Sparkling Cherry Juice", "111");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(629, "Crème Sparkling Beverage", "113");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(630, "Bitters Cocktail Mix", "110");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(631, "Olive Brine Cocktail Mix", "110");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(632, "Grapefruit Flavored Sparkling Water", "113");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(633, "Lemon Flavor Sparkling Water", "113");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(634, "Green Tea Beverage", "108");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(635, "Lemon Flavored Tea Beverage", "108");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(636, "Lemonade Flavored Mixed Tea Beverage", "108");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(637, "Mango Tea Beverage", "108");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(638, "White Tea Bluberry flavored Beverage", "108");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(639, "Non-Alcoholic Spirit Beverage", "110");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(640, "Sparkling Pomegranate Juice", "111");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(641, "Sparkling Spring Water", "113");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(642, "Still Spring Water", "113");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(643, "Sparkling Wildberry Juice", "111");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(644, "Sparkling Grape Juice", "111");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(645, "Sparkling Peach Juice", "111");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(646, "Non-Alcoholic Beer", "114");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(647, "Medium Roast Coffee Beans", "115");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(648, "Dark Roast Coffee Beans", "116");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(649, "Medium Roast Ground Coffee", "115");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(650, "Medium Roast Decaf Coffee", "115");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(651, "Espresso Lina's Coffee", "117");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(652, "Dark Roast Lina's Coffee", "116");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(653, "Medium Roast Lina's Coffee", "115");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(654, "Blend Roast Coffee Ground Coffee", "118");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(655, "Espresso Ground Coffee", "117");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(656, "Dark Coffee Ground Coffee", "116");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(657, "Flavor Blend Black Tea", "119");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(658, "Jasmine Flavor Blend White Tea", "120");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(659, "Supreme Earl Grey Black Tea", "119");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(660, "Herbal White Tea", "120");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(661, "Flavor Blend Green Tea", "121");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(662, "Ginger Black Tea", "119");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(663, "Flavor Blend White Tea", "120");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(664, "Earl Grey Black Tea", "119");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(665, "Organic Chamomile White Tea", "120");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(666, "Whole Leaf Black Tea", "119");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(667, "Whole Leaf Green Tea", "121");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(668, "Herbal Black Tea", "119");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(669, "Mao Feng Shui Green Tea", "121");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(670, "Italian Lemon Juice", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(671, "Italian Lime Juice", "97");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(672, "Type '00'", "122");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(673, "Classic Chestnut Spread", "123");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(674, "Classic Chocolate Spread", "124");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(675, "Cookie Butter Spread", "124");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(676, "Jarred Whole Chestnuts", "125");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(677, "Raspberry Spread", "123");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(678, "Plum Butter Jam", "126");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(679, "Chesnut Spread", "123");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(680, "Rosehip Jam", "126");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(681, "Blackberry Jam", "126");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(682, "Sour cherry Jam", "126");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(683, "Strawberry Jam", "126");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(684, "Fig Spread", "123");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(685, "Tangerine Jam", "126");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(686, "Fig Jam", "126");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(687, "Orange Jam", "126");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(688, "Raspberry Jam", "123");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(689, "Mixed fruit Jam", "123");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(690, "Peach Jam", "126");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(691, "White Honey", "127");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(692, "Buckwheat Honey", "127");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(693, "Flowers in Syrup", "107");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(694, "Orange Fig Spread", "123");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(695, "Flowers in Rose syrup", "107");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(696, "Blood Orange Jam", "126");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(697, "Lemon Curd", "126");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(698, "Cranberry Brandy Sauce", "123");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(699, "Deluxe Spread Pear Williams", "126");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(700, "Mint Jelly", "126");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(701, "Domestic Honey", "127");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(702, "Mediterranean Honey.", "127");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(703, "Cherry Jam Spread", "126");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(704, "Italian Mostarda", "128");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(705, "Almond Syrup", "107");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(706, "Organic Agave Nectar", "107");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(707, "Black cherry syrup", "107");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(708, "Vanilla Syrup", "107");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(709, "Strawberry Syrup", "107");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(710, "Hazelnut Syrup", "107");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(711, "White Chocolate Syrup", "107");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(712, "Sugar Free Hazelnut Syrup", "107");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(713, "Lemon Syrup", "107");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(714, "Pomegranate Molasses", "128");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(715, "Lime Syrup", "107");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(716, "Black Strap Molasses", "128");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(717, "Franch Coffee Trufle", "129");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(718, "Franch Hazelnut Truffle", "129");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(719, "Individually Wrapped Chocolate", "129");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(720, "Classic Chocolate Bar", "130");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(721, "Almond Chocolate Bar", "130");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(722, "Ginger Candy", "129");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(723, "Coconut Chocolate Bar", "130");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(724, "Peanut Butter Chocolate Bar", "130");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(725, "Raisin Chocolate Bar", "130");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(726, "Mint Chocolate Bar", "130");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(727, "Strawberry Cookie", "131");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(728, "Dark Chocolate Biscuit", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(729, "Coconut Biscuit", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(730, "Lemon Wafers", "131");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(731, "Vanilla Wafers", "131");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(732, "Peanut Wafers", "131");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(733, "Casarecci Biscuits", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(734, "Softbread Cookies", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(735, "Ciambelle Biscuits ", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(736, "Bite Size Wafer", "131");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(737, "Almond Biscuits", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(738, "Lemon Biscuits", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(739, "Chocolate Biscuits", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(740, "Orange Biscuits", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(741, "Orange Fillings", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(742, "Cherry Fillings", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(743, "Lady Fingers Biscuits", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(744, "Biscuit with Hazelnut Filling", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(745, "Biscuit with Fragola Filling", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(746, "Biscuit with Apricot Filling", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(747, "Biscuit with Cocoa Filling", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(748, "Ready to Make Kit Tiramisu", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(749, "Glazed Puff Pastry", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(750, "Wafer with Hazelnut Filling", "131");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(751, "Wafer with Chocolate Filling", "131");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(752, "Wafer with Lemon and Orange Filling", "131");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(753, "Croissant with Chocolate Filling", "132");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(754, "Rosmarino", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(755, "Ziti ", "134");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(756, "Lasagne", "135");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(757, "Lasagne ", "135");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(758, "Orecchiette ", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(759, "Penne Rigate", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(760, "Rigatoni", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(761, "Farfelle", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(762, "Trotiglioni ", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(763, "Fusilli", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(764, "Seme di melone", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(765, "Stellette", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(766, "Tubetti ", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(767, "Spaghetti", "135");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(768, "Casarecce ", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(769, "Tagliatelle all'uovo", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(770, "Macaroni & Cheese", "134");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(771, "Tortiglioni", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(772, "Italian Traditional", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(773, "Radiatori", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(774, "German Traditional", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(775, "All'Uovo", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(776, "Organic pasta", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(777, "Cannellloni", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(778, "Egg Noodles ", "133");
INSERT INTO `catalog_types` (id, name, subcategory_id) VALUES(779, "Classic Pizza Spice", "50");

/*Catalog - Container*/
INSERT INTO `catalog_packaging_containers`(id, name) VALUES(7, "box");
INSERT INTO `catalog_packaging_containers`(id, name) VALUES(8, "container");
INSERT INTO `catalog_packaging_containers`(id, name) VALUES(9, "cube");
INSERT INTO `catalog_packaging_containers`(id, name) VALUES(10, "tablet");
INSERT INTO `catalog_packaging_containers`(id, name) VALUES(11, "batch");
INSERT INTO `catalog_packaging_containers`(id, name) VALUES(12, "cruet");
INSERT INTO `catalog_packaging_containers`(id, name) VALUES(13, "bag");

/*Catalog - Volumes*/
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(61, "500gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(62, "314ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(63, "580ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(64, "425ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(65, "398ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(66, "540ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(67, "1kg");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(68, "750gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(69, "90gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(70, "12gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(71, "11gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(72, "136gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(73, "170gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(74, "369ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(75, "111gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(76, "115gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(77, "114gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(78, "220gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(79, "85gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(80, "99gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(81, "190gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(82, "150gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(83, "250gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(84, "160gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(85, "175gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(86, "169gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(87, "110gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(88, "142gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(89, "213gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(90, "199ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(91, "70gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(92, "113gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(93, "454gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(94, "240gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(95, "210gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(96, "180gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(97, "130gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(98, "15gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(99, "40gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(100, "55gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(101, "60gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(102, "25gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(103, "45gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(104, "375gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(105, "105gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(106, "46gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(107, "32gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(108, "57ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(109, "150ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(110, "148ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(111, "177ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(112, "125ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(113, "142ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(114, "24gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(115, "155ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(116, "135ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(117, "510gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(118, "226gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(119, "295ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(120, "850gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(121, "850ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(122, "930gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(123, "212ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(124, "190ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(125, "180ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(126, "144gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(127, "106gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(128, "149gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(129, "80ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(130, "532ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(131, "453gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(132, "680ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(133, "720ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(134, "213ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(135, "240ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(136, "380ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(137, "680gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(138, "796ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(139, "650ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(140, "720gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(141, "127gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(142, "139gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(143, "340gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(144, "370ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(145, "950ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(146, "800gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(147, "255ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(148, "320gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(149, "170ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(150, "1.9L");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(151, "900gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(152, "227ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(153, "400ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(154, "283gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(155, "400gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(156, "700ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(157, "591ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(158, "946ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(159, "1.5L");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(160, "300ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(161, "600ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(162, "118ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(163, "310ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(164, "325ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(165, "350ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(166, "502ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(167, "275ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(168, "800ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(169, "225gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(170, "2.5lb");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(171, "66gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(172, "36gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(173, "39.2gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(174, "50gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(175, "30gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(176, "22gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(177, "37gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(178, "42gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(179, "725gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(180, "350gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(181, "420gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(182, "290ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(183, "340ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(184, "350gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(185, "370gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(186, "592ml");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(187, "143gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(188, "145gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(189, "700gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(190, "147gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(191, "280gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(192, "265gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(193, "330gm");
INSERT INTO `catalog_packaging_volumes`(id, name) VALUES(194, "230gm");

